name: TestNG Appium CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run Tests on Emulator
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Step 3: Install Maven dependencies
    - name: Install Maven
      uses: actions/setup-java@v3
      with:
        cache: maven
        java-version: '11'

    # Step 4: Set up Android environment
    - name: Set up Android SDK
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Nexus_5X
        emulator-options: "-no-window -no-audio"

    # Step 5: Start Appium server
    - name: Start Appium Server
      run: |
        npm install -g appium
        appium --log-level error &

    # Step 6: Run app tests
    - name: Run Maven Tests
      run: mvn test -DsuiteXmlFile=testng_CounterApp_android_Emulator.xml -X

    # Step 7: Archive Extent Report
    - name: Archive Test Report
      uses: actions/upload-artifact@v3
      with:
        name: extent-report
        path: target/extent-reports/ 
